import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './css/globals.css';
import MainNav from '@/components/nav/nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <MainNav />
                {children}
            </body>
        </html>
    );
}
